# Generated by Django 5.1.7 on 2025-03-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solenizant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek', models.IntegerField(default=18)),
                ('stan_upojenia', models.CharField(choices=[('1', 'Aldente'), ('2', 'Pada'), ('3', 'Ze mną się nie napijesz?'), ('4', 'Stary krecik mocno śpi')], max_length=50)),
                ('data_urodzin', models.DateTimeField()),
                ('zdjecie1', models.ImageField(upload_to='images/')),
                ('zdjecie2', models.ImageField(upload_to='images/')),
                ('zdjecie3', models.ImageField(upload_to='images/')),
                ('zdjecie4', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
